In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('Downloads/LoanStats3d.csv',
    skipinitialspace=True,
    header=1)

/Users/laurakim/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68009401,72868139.0,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,C5,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,68354783,73244544.0,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,A4,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,68466916,73356753.0,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,A4,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,68466961,73356799.0,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,A2,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,68495092,73384866.0,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,E3,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0

In [4]:
data.shape

(421097, 111)

In [5]:
data['id'] = pd.to_numeric(data['id'], errors='coerce')
data['int_rate'] = pd.to_numeric(data['int_rate'].str.strip('%'), errors='coerce')

data.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'term', 'grade','emp_length','home_ownership','verification_status','mths_since_recent_inq','mths_since_recent_revol_delinq','mths_since_recent_bc_dlq','application_type','verification_status_joint','mths_since_last_major_derog','dti_joint','annual_inc_joint', 'last_pymnt_d','next_pymnt_d','last_credit_pull_d','issue_d','pymnt_plan','purpose','title','initial_list_status', 'addr_state', 'desc'], 1, inplace=True)

In [6]:
data.shape

(421097, 82)

In [7]:
data.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,loan_status,dti,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421092,36271333.0,38982739.0,13000.0,13000.0,13000.0,15.99,316.07,35000.0,Charged Off,30.90,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,36490806.0,39222577.0,12000.0,12000.0,12000.0,19.99,317.86,64400.0,Charged Off,27.19,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,36271262.0,38982659.0,20000.0,20000.0,20000.0,11.99,664.20,100000.0,Current,10.83,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data.drop(data.tail(2).index,inplace=True)

In [9]:
pd.get_dummies(data)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,loan_status_Charged Off,loan_status_Current,loan_status_Default,loan_status_Fully Paid,loan_status_In Grace Period,loan_status_Late (16-30 days),loan_status_Late (31-120 days)
0,68009401.0,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,...,31329.0,281300.0,13400.0,0,1,0,0,0,0,0
1,68354783.0,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,...,55387.0,12500.0,75635.0,0,1,0,0,0,0,0
2,68466916.0,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,...,68056.0,38400.0,82117.0,0,0,0,1,0,0,0
3,68466961.0,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,...,74920.0,41500.0,42503.0,0,1,0,0,0,0,0
4,68495092.0,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,...,18926.0,2750.0,18248.0,0,0,0,1,0,0,0
5,68506798.0,73396623.0,23000.0,23000.0,23000.0,8.49,471.77,64000.0,18.28,0.0,...,63886.0,39500.0,46662.0,0,1,0,0,0,0,0
6,68566886.0,73456723.0,29900.0,29900.0,29900.0,12.88,678.49,65000.0,21.77,0.0,...,42497.0,34000.0,15574.0,0,1,0,0,0,0,0
7,68577849.0,73467703.0,18000.0,18000.0,18000.0,11.99,400.31,112000.0,8.68,0.0,...,36127.0,69800.0,26210.0,0,0,0,1,0,0,0
8,66310712.0,71035433.0,35000.0,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,...,52226.0,62500.0,18000.0,0,1,0,0,0,0,0
9,68476807.0,73366655.0,10400.0,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,...,95768.0,20300.0,88097.0,0,0,0,1,0,0,0
10,68341763.0,72928789.0,20000.0,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,...,18696.0,6200.0,14877.0,0,1,0,0,0,0,0
11,68356421.0,73246236.0,22400.0,22400.0,22400.0,12.88,508.30,95000.0,22.98,0.0,...,184356.0,21000.0,191682.0,0,1,0,0,0,0,0
12,68426545.0,73316365.0,16000.0,16000.0,16000.0,12.88,363.07,70000.0,26.40,0.0,...,62407.0,45900.0,45838.0,0,1,0,0,0,0,0
13,68407277.0,73297111.0,3600.0,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,...,7746.0,2400.0,13734.0,0,1,0,0,0,0,0
14,68355089.0,73244858.0,24700.0,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,...,39475.0,79300.0,24667.0,0,0,0,1,0,0,0
15,68466926.0,73356763.0,10000.0,10000.0,10000.0,6.49,306.45,85000.0,13.07,0.0,...,27957.0,16400.0,30799.0,0,1,0,0,0,0,0
16,68338832.0,73542831.0,1400.0,1400.0,1400.0,12.88,47.10,64000.0,34.95,0.0,...,75258.0,34500.0,55501.0,0,1,0,0,0,0,0
17,68426831.0,73316657.0,11950.0,11950.0,11950.0,13.44,405.18,34000.0,10.20,0.0,...,12798.0,9400.0,4000.0,0,1,0,0,0,0,0
18,66624733.0,71350547.0,18000.0,18000.0,18000.0,19.48,471.70,150000.0,9.39,0.0,...,36247.0,10300.0,31319.0,0,1,0,0,0,0,0
19,68616873.0,73519699.0,8000.0,8000.0,8000.0,11.48,263.74,42000.0,34.80,0.0,...,113782.0,17000.0,135513.0,0,1,0,0,0,0,0
20,67275481.0,72077199.0,20000.0,20000.0,20000.0,8.49,631.26,85000.0,17.61,1.0,...,27937.0,14500.0,36144.0,0,1,0,0,0,0,0
21,68476668.0,73366513.0,20000.0,20000.0,20000.0,9.17,637.58,180000.0,14.67,0.0,...,116762.0,31500.0,46452.0,0,0,0,1,0,0,0
22,68476702.0,73366548.0,28000.0,28000.0,28000.0,13.44,949.38,125000.0,7.49,0.0,...,22780.0,29000.0,0.0,0,1,0,0,0,0,0
23,68436666.0,73326493.0,5000.0,5000.0,5000.0,13.44,169.54,79000.0,12.70,0.0,...,35653.0,4300.0,31791.0,0,1,0,0,0,0,0
24,68596180.0,73485987.0,20000.0,20000.0,20000.0,5.32,602.30,65000.0,18.83,0.0,...,15444.0,76200.0,30017.0,0,1,0,0,0,0,0
25,67849662.0,72708407.0,4225.0,4225.0,4225.0,14.85,146.16,35000.0,15.22,2.0,...,4888.0,2600.0,17522.0,0,1,0,0,0,0,0
26,68526883.0,73416719.0,15000.0,15000.0,15000.0,5.32,451.73,44000.0,15.34,0.0,...,17003.0,14300.0,0.0,0,1,0,0,0,0,0
27,68607141.0,73509983.0,17600.0,17600.0,17600.0,5.32,530.03,88000.0,26.59,0.0,...,80847.0,23600.0,92701.0,0,0,0,1,0,0,0
28,68476715.0,73366561.0,6000.0,6000.0,6000.0,7.49,186.61,100000.0,13.28,1.0,...,22741.0,3800.0,36083.0,0,1,0,0,0,0,0
29,67715283.0,72569997.0,16000.0,16000.0,16000.0,12.88,538.18,65000.0,18.96,0.0,...,39781.0,4700.0,71499.0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421065,36631385.0,39374138.0,13000.0,13000.0,13000.0,8.19,408.52,85000.0,8.05,1.0,...,19133.0,6500.0,20950.0,0,1,0,0,0,0,0
421066,36231083.0,38942474.0,15000.0,15000.0,15000.0,11.99,498.15,70000.0,8.47,0.0,...,15724.0,9600.0,7381.0,0,1,0,0,0,0,0
421067,36691397.0,39434133.0,20000.0,20000.0,20000.0,6.99,617.46,72000.0,27.24,0.0,...,52677.0,26700.0,46379.0,0,1,0,0,0,0,0
421068,36743377.0,39486112.0,4200.0,4200.0,4200.0,15.99,147.64,48000.0,36.93,0.0,...,45512.0,5600.0,40401.0,1,0,0,0,0,0,0
421069,36331554.0,39042967.0,26950.0,26950.0,26950.0,8.19,846.88,54000.0,18.11,0.0,...,41650.0,124600.0,8333.0,0,0,0,1,0,0,0
421070,36460697.0,39182359.0,23000.0,23000.0,23000.0,15.59,554.32,50000.0,31.95,0.0,...,48978.0,60800.0,13910.0,0,1,0,0,0,0,0
421071,35773415.0,38468842.0,18700.0,18700.0,18700.0,17.86,473.44,52000.0,11.28,0.0,...,40164.0,10000.0,32299.0,0,0,0,1,0,0,0
421072,36250801.0,38962184.0,6000.0,6000.0,6000.0,17.86,216.50,90000.0,2.84,0.0,...,14906.0,1900.0,8085.0,0,1,0,0,0,0,0
421073,36371802.0,39103231.0,15000.0,15000.0,15000.0,11.44,329.44,57000.0,15.77,0.0,...,33529.0,22500.0,21574.0,0,1,0,0,0,0,0
421074,36440728.0,39152101.0,25000.0,25000.0,25000.0,15.99,607.82,103000.0,5.27,0.0,...,17275.0,17500.0,0.0,0,0,0,0,0,0,1
421075,36361815.0,39093260.0,26500.0,26500.0,26500.0,8.67,545.87,92000.0,29.60,1.0,...,91768.0,67600.0,33501.0,0,1,0,0,0,0,0
421076,35591131.0,38288343.0,25000.0,25000.0,25000.0,15.59,602.52,55000.0,5.52,0.0,...,13860.0,20900.0,0.0,0,0,0,1,0,0,0
421077,36201871.0,38913321.0,21000.0,21000.0,21000.0,6.03,639.15,65000.0,17.09,0.0,...,36303.0,76300.0,36656.0,0,1,0,0,0,0,0
421078,36381756.0,39013193.0,8000.0,8000.0,8000.0,8.19,251.40,50000.0,17.62,0.0,...,38259.0,5800.0,39940.0,0,1,0,0,0,0,0
421079,36231724.0,38943173.0,12000.0,12000.0,12000.0,9.49,384.34,40000.0,25.65,1.0,...,20671.0,10500.0,16283.0,0,0,0,1,0,0,0
421080,36301729.0,39023153.0,10000.0,10000.0,10000.0,6.49,306.45,75000.0,33.66,0.0,...,88120.0,30300.0,117998.0,0,1,0,0,0,0,0
421081,36250208.0,38961532.0,13150.0,13150.0,13150.0,14.99,312.77,30000.0,1.00,0.0,...,672.0,20700.0,0.0,0,0,0,1,0,0,0
421082,36241316.0,38952731.0,6225.0,6225.0,6225.0,16.49,220.37,27000.0,18.58,0.0,...,8357.0,1800.0,12507.0,0,0,0,1,0,0,0
421083,36231718.0,38943165.0,10775.0,10775.0,10775.0,6.03,327.95,54000.0,13.22,1.0,...,24696.0,38700.0,19248.0,0,0,0,1,0,0,0
421084,36381704.0,39013139.0,7000.0,7000.0,7000.0,14.31,240.30,57000.0,16.80,2.0,...,32135.0,6900.0,33868.0,0,1,0,0,0,0,0
421085,36421485.0,39142898.0,4000.0,4000.0,4000.0,8.67,126.59,50000.0,12.63,0.0,...,18979.0,12900.0,28234.0,0,0,0,1,0,0,0
421086,35094480.0,37777829.0,7500.0,7500.0,7500.0,9.49,240.22,40000.0,25.63,0.0,...,18611.0,10700.0,21820.0,0,1,0,0,0,0,0
421087,36260758.0,38972123.0,10850.0,10850.0,10850.0,19.24,399.04,32000.0,29.44,0.0,...,28301.0,2500.0,27533.0,1,0,0,0,0,0,0
421088,36221446.0,38932858.0,11575.0,11575.0,11575.0,15.59,404.61,25400.0,27.08,0.0,...,19798.0,27500.0,1766.0,0,0,0,1,0,0,0
421089,36330911.0,39042282.0,12000.0,12000.0,12000.0,11.99,398.52,63000.0,23.69,1.0,...,112990.0,15400.0,98125.0,1,0,0,0,0,0,0
421090,36371250.0,39102635.0,10000.0,10000.0,10000.0,11.99,332.10,31000.0,28.69,0.0,...,25274.0,9200.0,15850.0,0,1,0,0,0,0,0
421091,36441262.0,39152692.0,24000.0,24000.0,24000.0,11.99,797.03,79000.0,3.90,0.0,...,8621.0,9000.0,0.0,0,1,0,0,0,0,0
421092,36271333.0,38982739.0,13000.0,13000.0,13000.0,15.99,316.07,35000.0,30.90,0.0,...,34178.0,10600.0,33239.0,1,0,0,0,0,0,0
421093,36490806.0,39222577.0,12000.0,12000.0,12000.0,19.99,317.86,64400.0,27.19,1.0,...,58418.0,9700.0,69919.0,1,0,0,0,0,0,0
421094,36271262.0,38982659.0,20000.0,20000.0,20000.0,11.99,664.20,100000.0,10.83,0.0,...,33307.0,41700.0,0.0,0,1,0,0,0,0,0

In [10]:
corr_table=pd.DataFrame(data.corr())

In [11]:
data.loan_status.unique()

array(['Current', 'Fully Paid', 'Charged Off', 'Late (31-120 days)',
       'In Grace Period', 'Default', 'Late (16-30 days)'], dtype=object)

In [12]:
list(data.columns)

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'int_rate',
 'installment',
 'annual_inc',
 'loan_status',
 'dti',
 'delinq_2yrs',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'total_acc',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_amnt',
 'collections_12_mths_ex_med',
 'policy_code',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_il_6m',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit']

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 421095 entries, 0 to 421094
Data columns (total 82 columns):
id                            421095 non-null float64
member_id                     421095 non-null float64
loan_amnt                     421095 non-null float64
funded_amnt                   421095 non-null float64
funded_amnt_inv               421095 non-null float64
int_rate                      421095 non-null float64
installment                   421095 non-null float64
annual_inc                    421095 non-null float64
loan_status                   421095 non-null object
dti                           421095 non-null float64
delinq_2yrs                   421095 non-null float64
inq_last_6mths                421095 non-null float64
mths_since_last_delinq        217133 non-null float64
mths_since_last_record        74415 non-null float64
open_acc                      421095 non-null float64
pub_rec                       421095 non-null float64
revol_bal                     421095 non-null float64
total_acc                     421095 non-null float64
out_prncp                     421095 non-null float64
out_prncp_inv                 421095 non-null float64
total_pymnt                   421095 non-null float64
total_pymnt_inv               421095 non-null float64
total_rec_prncp               421095 non-null float64
total_rec_int                 421095 non-null float64
total_rec_late_fee            421095 non-null float64
recoveries                    421095 non-null float64
collection_recovery_fee       421095 non-null float64
last_pymnt_amnt               421095 non-null float64
collections_12_mths_ex_med    421095 non-null float64
policy_code                   421095 non-null float64
acc_now_delinq                421095 non-null float64
tot_coll_amt                  421095 non-null float64
tot_cur_bal                   421095 non-null float64
open_acc_6m                   21372 non-null float64
open_il_6m                    21372 non-null float64
open_il_12m                   21372 non-null float64
open_il_24m                   21372 non-null float64
mths_since_rcnt_il            20810 non-null float64
total_bal_il                  21372 non-null float64
il_util                       18617 non-null float64
open_rv_12m                   21372 non-null float64
open_rv_24m                   21372 non-null float64
max_bal_bc                    21372 non-null float64
all_util                      21372 non-null float64
total_rev_hi_lim              421095 non-null float64
inq_fi                        21372 non-null float64
total_cu_tl                   21372 non-null float64
inq_last_12m                  21372 non-null float64
acc_open_past_24mths          421095 non-null float64
avg_cur_bal                   421095 non-null float64
bc_open_to_buy                417132 non-null float64
bc_util                       416868 non-null float64
chargeoff_within_12_mths      421095 non-null float64
delinq_amnt                   421095 non-null float64
mo_sin_old_il_acct            408841 non-null float64
mo_sin_old_rev_tl_op          421095 non-null float64
mo_sin_rcnt_rev_tl_op         421095 non-null float64
mo_sin_rcnt_tl                421095 non-null float64
mort_acc                      421095 non-null float64
mths_since_recent_bc          417297 non-null float64
num_accts_ever_120_pd         421095 non-null float64
num_actv_bc_tl                421095 non-null float64
num_actv_rev_tl               421095 non-null float64
num_bc_sats                   421095 non-null float64
num_bc_tl                     421095 non-null float64
num_il_tl                     421095 non-null float64
num_op_rev_tl                 421095 non-null float64
num_rev_accts                 421094 non-null float64
num_rev_tl_bal_gt_0           421095 non-null float64
num_sats                      421095 non-null float64
num_tl_120dpd_2m              401865 non-null float64
num_tl_30dpd                  421095 non-null float64
num_tl_90g_dpd_24m            421095 non-null float64
num_tl_op_past_12m            421095 non-null float64
pct_tl_nvr_dlq                421095 non-null float64
percent_bc_gt_75              416856 non-null float64
pub_rec_bankruptcies          421095 non-null float64
tax_liens                     421095 non-null float64
tot_hi_cred_lim               421095 non-null float64
total_bal_ex_mort             421095 non-null float64
total_bc_limit                421095 non-null float64
total_il_high_credit_limit    421095 non-null float64
dtypes: float64(81), object(1)
memory usage: 266.7+ MB

In [14]:
data.dtypes

id                            float64
member_id                     float64
loan_amnt                     float64
funded_amnt                   float64
funded_amnt_inv               float64
int_rate                      float64
installment                   float64
annual_inc                    float64
loan_status                    object
dti                           float64
delinq_2yrs                   float64
inq_last_6mths                float64
mths_since_last_delinq        float64
mths_since_last_record        float64
open_acc                      float64
pub_rec                       float64
revol_bal                     float64
total_acc                     float64
out_prncp                     float64
out_prncp_inv                 float64
total_pymnt                   float64
total_pymnt_inv               float64
total_rec_prncp               float64
total_rec_int                 float64
total_rec_late_fee            float64
recoveries                    float64
collection_recovery_fee       float64
last_pymnt_amnt               float64
collections_12_mths_ex_med    float64
policy_code                   float64
                               ...
chargeoff_within_12_mths      float64
delinq_amnt                   float64
mo_sin_old_il_acct            float64
mo_sin_old_rev_tl_op          float64
mo_sin_rcnt_rev_tl_op         float64
mo_sin_rcnt_tl                float64
mort_acc                      float64
mths_since_recent_bc          float64
num_accts_ever_120_pd         float64
num_actv_bc_tl                float64
num_actv_rev_tl               float64
num_bc_sats                   float64
num_bc_tl                     float64
num_il_tl                     float64
num_op_rev_tl                 float64
num_rev_accts                 float64
num_rev_tl_bal_gt_0           float64
num_sats                      float64
num_tl_120dpd_2m              float64
num_tl_30dpd                  float64
num_tl_90g_dpd_24m            float64
num_tl_op_past_12m            float64
pct_tl_nvr_dlq                float64
percent_bc_gt_75              float64
pub_rec_bankruptcies          float64
tax_liens                     float64
tot_hi_cred_lim               float64
total_bal_ex_mort             float64
total_bc_limit                float64
total_il_high_credit_limit    float64
Length: 82, dtype: object

In [15]:
data.dropna(inplace=True)

In [16]:
len(data)

1661

In [17]:
data.shape

(1661, 82)

In [18]:
data['loan_status'].unique()

array(['Current', 'Fully Paid', 'Late (31-120 days)', 'In Grace Period',
       'Charged Off', 'Late (16-30 days)', 'Default'], dtype=object)

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
x=data.drop('loan_status', 1)
y=data.loc[:,['loan_status']].values

In [21]:
x=StandardScaler().fit_transform(x)

In [23]:
from sklearn.decomposition import PCA

In [24]:
#pca=PCA(n_components=2)

In [25]:
#principalComponents=pca.fit_transform(x)
#principalDf=pd.DataFrame(data=principalComponents, columns=['PC1','PC2'])

In [26]:
#print(principalDf)

In [27]:
#target_column=pd.DataFrame(data['loan_status']).reset_index()

In [28]:
#finalDf=pd.concat([principalDf, target_column], axis=1)
#finalDf.head()

In [29]:
# fig=plt.figure(figsize=(8,8))
# ax=fig.add_subplot(1,1,1)
# ax.set_xlabel('pc1', fontsize=15)
# ax.set_ylabel('pc2', fontsize=15)
# ax.set_title('2 component PCA', fontsize=20)

# ax.scatter(finalDf.loc[finalDf['loan_status']=='Current','PC1'], 
#            finalDf.loc[finalDf['loan_status']=='Current','PC2'], color='r')
# ax.scatter(finalDf.loc[finalDf['loan_status']=='Fully Paid','PC1'], 
#            finalDf.loc[finalDf['loan_status']=='Fully Paid','PC2'], color='b')
# ax.scatter(finalDf.loc[finalDf['loan_status']=='Late (31-120 days)','PC1'], 
#            finalDf.loc[finalDf['loan_status']=='Late (31-120 days)','PC2'], color='g')
# ax.scatter(finalDf.loc[finalDf['loan_status']=='In Grace Period','PC1'], 
#            finalDf.loc[finalDf['loan_status']=='In Grace Period','PC2'], color='c')
# ax.scatter(finalDf.loc[finalDf['loan_status']=='Charged Off','PC1'], 
#            finalDf.loc[finalDf['loan_status']=='Charged Off','PC2'], color='y')
# ax.scatter(finalDf.loc[finalDf['loan_status']=='Late (16-30 days)','PC1'], 
#            finalDf.loc[finalDf['loan_status']=='Late (16-30 days)','PC2'], color='w')
# ax.scatter(finalDf.loc[finalDf['loan_status']=='Default','PC1'], 
#            finalDf.loc[finalDf['loan_status']=='Default','PC2'], color='k')

In [30]:
#pca.explained_variance_ratio_*100

In [74]:
pca=PCA(n_components=35)      
principalComponents=pca.fit_transform(x)
pca.explained_variance_ratio_*100

array([13.23998276,  9.95198332,  6.91999743,  5.73429341,  4.18512894,
        3.6744335 ,  3.18845154,  2.906808  ,  2.80459945,  2.60280807,
        2.50610364,  2.46688116,  2.19850227,  2.07695106,  1.93253755,
        1.75890581,  1.71354415,  1.68407807,  1.46791095,  1.43416711,
        1.3558621 ,  1.3350764 ,  1.27580942,  1.21908297,  1.19906066,
        1.1481137 ,  1.11672339,  1.05961384,  1.01610703,  0.96106126,
        0.91545202,  0.87776939,  0.83376549,  0.8148779 ,  0.78215632])

In [75]:
sum(pca.explained_variance_ratio_*100)

90.35860007430958

In [76]:
#loading score for pc1:
#to see which top 10 explanatory features have the largest influence on separating the targets
#based on their magnitude (take abs)

In [77]:
loading_scores=pd.Series(pca.components_[0])
sorted_loading_scores = loading_scores.abs().sort_values(ascending=False)

In [78]:
#getting the feature names in PC1:
features = sorted_loading_scores[0:10].index.values

In [79]:
print(loading_scores[features])

13    0.233692
68    0.233524
65    0.221075
62    0.202377
47    0.198981
16    0.196887
67    0.194979
61    0.193576
66    0.185179
60    0.178011
dtype: float64

In [80]:
#very similar values.

In [81]:
#loading score for pc2:
#to see which top 10 explanatory features have the largest influence on separating the targets
#based on their magnitude (take abs)

In [82]:
loading_scores=pd.Series(pca.components_[1])
sorted_loading_scores = loading_scores.abs().sort_values(ascending=False)

In [83]:
features = sorted_loading_scores[0:].index.values

In [84]:
print(loading_scores[features])

4     2.743279e-01
2     2.743181e-01
3     2.743181e-01
6     2.644558e-01
22    2.189690e-01
17    2.169628e-01
18    2.169587e-01
19    1.916782e-01
20    1.916636e-01
40   -1.764561e-01
39   -1.728216e-01
72   -1.656707e-01
47   -1.622254e-01
48    1.546976e-01
41    1.439291e-01
32   -1.436259e-01
21    1.435009e-01
65   -1.423323e-01
7     1.322267e-01
55    1.275713e-01
77    1.264774e-01
31    1.229356e-01
13   -1.169805e-01
56    1.166036e-01
68   -1.162618e-01
61   -1.137349e-01
67   -1.125174e-01
58    1.121338e-01
10   -1.101712e-01
66   -1.101239e-01
          ...
12   -3.802227e-02
37    3.784433e-02
23    3.686035e-02
44   -3.611810e-02
53    3.432805e-02
54    3.142709e-02
36    2.961400e-02
14    2.674284e-02
11   -2.600800e-02
9     2.596455e-02
5     2.476705e-02
64   -2.456367e-02
24   -1.996370e-02
25   -1.992558e-02
33   -1.914726e-02
29    1.643251e-02
0    -1.518677e-02
42    1.457058e-02
49    1.202948e-02
70    1.057526e-02
27   -1.037754e-02
71    9.964866e-03
69    9.809993e-03
51   -6.885146e-03
1    -4.858119e-03
59    3.586356e-03
45   -3.298712e-03
30    1.000956e-03
52    8.538790e-04
28    9.302876e-22
Length: 81, dtype: float64

In [85]:
loading_scores=pd.Series(pca.components_[2])
sorted_loading_scores = loading_scores.abs().sort_values(ascending=False)

In [86]:
features = sorted_loading_scores[0:].index.values

In [87]:
print(loading_scores[features])

37    2.789829e-01
64    2.680458e-01
80    2.617328e-01
42    2.576699e-01
35    2.524483e-01
78    2.480076e-01
33    2.351017e-01
34    2.211123e-01
38    1.917057e-01
62   -1.721723e-01
79   -1.626135e-01
49   -1.591821e-01
60   -1.494906e-01
44    1.480257e-01
63   -1.466683e-01
65   -1.450687e-01
43   -1.429998e-01
31    1.384758e-01
36   -1.362839e-01
67   -1.283231e-01
61   -1.274355e-01
48    1.263423e-01
66   -1.239179e-01
77    1.101085e-01
46    1.073408e-01
16    1.036046e-01
45    9.959147e-02
5     9.804340e-02
74    9.204578e-02
53    9.024162e-02
          ...
3    -3.465930e-02
2    -3.465930e-02
4    -3.460450e-02
6    -3.267425e-02
55    3.013453e-02
57    2.679317e-02
14   -2.665258e-02
0     2.386922e-02
11   -2.243670e-02
23   -2.200205e-02
12    1.877743e-02
7     1.763251e-02
59    1.670932e-02
51    1.580584e-02
17   -1.559827e-02
18   -1.555693e-02
26   -1.478535e-02
70   -1.387817e-02
1     1.380664e-02
22    1.178829e-02
68    1.148980e-02
13    1.057265e-02
75    1.054889e-02
29   -6.990404e-03
73    4.479653e-03
30    4.160707e-03
27   -4.062458e-03
52   -3.692594e-03
69    3.151991e-03
28   -3.519628e-21
Length: 81, dtype: float64

In [88]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = x
Y = data['loan_status']

cross_val_score(rfc, X, Y, cv=5)

/Users/laurakim/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
/Users/laurakim/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/laurakim/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/laurakim/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/laurakim/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/Users/laurakim/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.94925373, 0.95209581, 0.95481928, 0.95468278, 0.96352584])